# Generated by Django 3.1.7 on 2021-06-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210611_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mahasiswa',
            old_name='name',
            new_name='nama',
        ),
    ]
